# -*- coding: utf-8 -*-
"""PHYS 6040 HW_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rCnVf2iwlfxDrTtkpFnUnNdXr5kqXjpA
"""

import math
import numpy as np
import random
from matplotlib import pyplot

trials=[pow(10,i) for i in range(7)]
probs=[]

pop=1000 #total population
smoke=350 #smokers
noSmoke=650 #non-smokers

#probabilities (used for case with replacement)
smokeProb=smoke/pop
noSmokeProb=noSmoke/pop

#with replacement
for l in trials:
  count=0
  #i repetitions up to a number of l total trials
  for i in range(l):
    #generate 10 random cases
    cases=np.array([random.uniform(0,1) for q in range(10)])
    #number of cases where rand >= prob of smoker
    numSmokers=np.sum(cases <= smokeProb)
    #exactly 4 out of 10 are smokers
    if numSmokers==4:
      count+=1
  probs.append(count/l)

pyplot.subplot(2,1,1)
pyplot.plot(trials, probs, color='blue', lw=2)
pyplot.xscale('log')
pyplot.ylim([0,0.3])
pyplot.axline((0,0.23767), (trials[len(trials)-1],0.23767))

pyplot.xlabel('Number of Trials')
pyplot.ylabel('Probability')
pyplot.title('With Replacement')
pyplot.show()


pyplot.subplot(2,1,1)
pyplot.plot(trials, [i-0.23767 for i in probs], color='blue', lw=2)
pyplot.xscale('log')
pyplot.ylim([-0.23767,0.05])
pyplot.axline((0,0), (trials[len(trials)-1],0))

pyplot.xlabel('Number of Trials')
pyplot.ylabel('Probability')
pyplot.title('With Replacement, Difference from 0.23767')
pyplot.show()

probsNoRep=[]
#without replacement
for l in trials:
  count=0
  #i repetitions up to a number of l total trials
  for i in range(l):
    numSmokers=0#number of smokers found in query
    pop=1000 #total population
    smoke=350 #smokers
    noSmoke=650 #non-smokers
    for q in range(10):#query 10 smokers
      ans=random.uniform(0,1)
      if ans <= smoke/pop:
        smoke-=1
        numSmokers+=1
      else:
        noSmoke-=1
      pop-=1
    if numSmokers==4:
      count+=1
  probsNoRep.append(count/l)

pyplot.subplot(1,1,1)
pyplot.plot(trials, probsNoRep, color='blue', lw=2)
pyplot.xscale('log')
pyplot.ylim([0,0.3])
pyplot.axline((0,0.23881), (trials[len(trials)-1],0.23881))

pyplot.xlabel('Number of Trials')
pyplot.ylabel('Probability')
pyplot.title('Without Replacement')
pyplot.show()

pyplot.subplot(2,1,1)
pyplot.plot(trials, [i-0.23881 for i in probsNoRep], color='blue', lw=2)
pyplot.xscale('log')
pyplot.ylim([-0.23881,0.05])
pyplot.axline((0,0), (trials[len(trials)-1],0))

pyplot.xlabel('Number of Trials')
pyplot.ylabel('Probability')
pyplot.title('Without Replacement, Difference from 0.23881')
pyplot.show()

